name: deploy-to-artifact-registry
run-name: ${{github.repository}} deployed to GCP Artifact-Registry
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout my branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: setup python  
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "key.json"
        json: ${{ secrets.CENTRAL_INFRA_JSON}}
    - name: install to GCP AR
      run: |
        echo install Twine
        pip install twine
        echo install build
        pip install --upgrade pip build
        echo install Google Keyring
        pip install keyrings.google-artifactregistry-auth
        export GOOGLE_APPLICATION_CREDENTIALS=key.json
        python -m build --sdist --wheel --outdir dist/
        python -m twine upload --verbose --repository-url ${{vars.ARTIFACT_REGISTRY_REPO_URL}} dist/*